package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/yourusername/iot-platform/services/api-gateway/graph/generated"
	"github.com/yourusername/iot-platform/services/api-gateway/graph/model"
)

// CreateDevice is the resolver for the createDevice field.
func (r *mutationResolver) CreateDevice(ctx context.Context, input model.CreateDeviceInput) (*model.Device, error) {
	panic(fmt.Errorf("not implemented: CreateDevice - createDevice"))
}

// UpdateDevice is the resolver for the updateDevice field.
func (r *mutationResolver) UpdateDevice(ctx context.Context, input model.UpdateDeviceInput) (*model.Device, error) {
	panic(fmt.Errorf("not implemented: UpdateDevice - updateDevice"))
}

// DeleteDevice is the resolver for the deleteDevice field.
func (r *mutationResolver) DeleteDevice(ctx context.Context, id string) (*model.DeleteResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDevice - deleteDevice"))
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*model.Device, error) {
	panic(fmt.Errorf("not implemented: Device - device"))
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context, page *int, pageSize *int, typeArg *string, status *model.DeviceStatus) (*model.DeviceConnection, error) {
	panic(fmt.Errorf("not implemented: Devices - devices"))
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.Stats, error) {
	panic(fmt.Errorf("not implemented: Stats - stats"))
}

// DeviceUpdated is the resolver for the deviceUpdated field.
func (r *subscriptionResolver) DeviceUpdated(ctx context.Context) (<-chan *model.Device, error) {
	panic(fmt.Errorf("not implemented: DeviceUpdated - deviceUpdated"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
