package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/yourusername/iot-platform/services/api-gateway/graph/generated"
	"github.com/yourusername/iot-platform/services/api-gateway/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	return r.RegisterImpl(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	return r.LoginImpl(ctx, input)
}

// CreateDevice is the resolver for the createDevice field.
func (r *mutationResolver) CreateDevice(ctx context.Context, input model.CreateDeviceInput) (*model.Device, error) {
	return r.CreateDeviceImpl(ctx, input)
}

// UpdateDevice is the resolver for the updateDevice field.
func (r *mutationResolver) UpdateDevice(ctx context.Context, input model.UpdateDeviceInput) (*model.Device, error) {
	return r.UpdateDeviceImpl(ctx, input)
}

// DeleteDevice is the resolver for the deleteDevice field.
func (r *mutationResolver) DeleteDevice(ctx context.Context, id string) (*model.DeleteResult, error) {
	return r.DeleteDeviceImpl(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.MeImpl(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, page *int, pageSize *int, role *string) (*model.UserConnection, error) {
	return r.UsersImpl(ctx, page, pageSize, role)
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*model.Device, error) {
	return r.DeviceImpl(ctx, id)
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context, page *int, pageSize *int, typeArg *string, status *model.DeviceStatus) (*model.DeviceConnection, error) {
	return r.DevicesImpl(ctx, page, pageSize, typeArg, status)
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.Stats, error) {
	return r.StatsImpl(ctx)
}

// DeviceTelemetry is the resolver for the deviceTelemetry field.
func (r *queryResolver) DeviceTelemetry(ctx context.Context, deviceID string, metricName string, from int, to int, limit *int) (*model.TelemetrySeries, error) {
	return r.DeviceTelemetryImpl(ctx, deviceID, metricName, from, to, limit)
}

// DeviceTelemetryAggregated is the resolver for the deviceTelemetryAggregated field.
func (r *queryResolver) DeviceTelemetryAggregated(ctx context.Context, deviceID string, metricName string, from int, to int, interval string) ([]*model.TelemetryAggregation, error) {
	return r.DeviceTelemetryAggregatedImpl(ctx, deviceID, metricName, from, to, interval)
}

// DeviceLatestMetric is the resolver for the deviceLatestMetric field.
func (r *queryResolver) DeviceLatestMetric(ctx context.Context, deviceID string, metricName string) (*model.TelemetryPoint, error) {
	return r.DeviceLatestMetricImpl(ctx, deviceID, metricName)
}

// DeviceMetrics is the resolver for the deviceMetrics field.
func (r *queryResolver) DeviceMetrics(ctx context.Context, deviceID string) ([]string, error) {
	return r.DeviceMetricsImpl(ctx, deviceID)
}

// DeviceUpdated is the resolver for the deviceUpdated field.
func (r *subscriptionResolver) DeviceUpdated(ctx context.Context) (<-chan *model.Device, error) {
	panic(fmt.Errorf("not implemented: DeviceUpdated - deviceUpdated"))
}

// TelemetryReceived is the resolver for the telemetryReceived field.
func (r *subscriptionResolver) TelemetryReceived(ctx context.Context, deviceID string) (<-chan *model.TelemetryPoint, error) {
	// Subscribe to telemetry updates for this device
	ch := r.Broker.Subscribe(deviceID)

	// Cleanup when context is done (client disconnects)
	go func() {
		<-ctx.Done()
		r.Broker.Unsubscribe(deviceID, ch)
	}()

	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
