// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevicesByStatus = `-- name: CountDevicesByStatus :one
SELECT COUNT(*) FROM devices
WHERE status = $1
`

func (q *Queries) CountDevicesByStatus(ctx context.Context, status DeviceStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (
    id,
    name,
    type,
    status,
    created_at,
    last_seen,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, type, status, created_at, last_seen, metadata
`

type CreateDeviceParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Status    DeviceStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	Metadata  []byte             `json:"metadata"`
}

// IoT Platform - Device Manager Queries
// SQL queries with sqlc annotations for type-safe code generation
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.CreatedAt,
		arg.LastSeen,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, type, status, created_at, last_seen, metadata FROM devices
WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, type, status, created_at, last_seen, metadata FROM devices
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDevicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeen,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByStatus = `-- name: ListDevicesByStatus :many
SELECT id, name, type, status, created_at, last_seen, metadata FROM devices
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDevicesByStatusParams struct {
	Status DeviceStatus `json:"status"`
	Limit  int32        `json:"limit"`
	Offset int32        `json:"offset"`
}

func (q *Queries) ListDevicesByStatus(ctx context.Context, arg ListDevicesByStatusParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeen,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByType = `-- name: ListDevicesByType :many
SELECT id, name, type, status, created_at, last_seen, metadata FROM devices
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDevicesByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListDevicesByType(ctx context.Context, arg ListDevicesByTypeParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeen,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET
    name = $1,
    status = $2,
    metadata = $3,
    last_seen = $4
WHERE id = $5
RETURNING id, name, type, status, created_at, last_seen, metadata
`

type UpdateDeviceParams struct {
	Name     string             `json:"name"`
	Status   DeviceStatus       `json:"status"`
	Metadata []byte             `json:"metadata"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
	ID       pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.Name,
		arg.Status,
		arg.Metadata,
		arg.LastSeen,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}
