// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceStatus string

const (
	DeviceStatusUNKNOWN     DeviceStatus = "UNKNOWN"
	DeviceStatusONLINE      DeviceStatus = "ONLINE"
	DeviceStatusOFFLINE     DeviceStatus = "OFFLINE"
	DeviceStatusERROR       DeviceStatus = "ERROR"
	DeviceStatusMAINTENANCE DeviceStatus = "MAINTENANCE"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

// IoT devices managed by the platform
type Device struct {
	// Unique device identifier (UUID)
	ID pgtype.UUID `json:"id"`
	// Human-readable device name
	Name string `json:"name"`
	// Device type (sensor, actuator, gateway, etc.)
	Type string `json:"type"`
	// Current operational status
	Status DeviceStatus `json:"status"`
	// Device registration timestamp
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last activity timestamp
	LastSeen pgtype.Timestamptz `json:"last_seen"`
	// Flexible key-value storage for device-specific data
	Metadata []byte `json:"metadata"`
}

// User accounts for authentication and authorization
type User struct {
	// Unique user identifier (UUID)
	ID pgtype.UUID `json:"id"`
	// User email address (unique, used for login)
	Email string `json:"email"`
	// Bcrypt hashed password (never store plain text)
	PasswordHash string `json:"password_hash"`
	// User full name
	Name string `json:"name"`
	// User role: admin, user, or device
	Role string `json:"role"`
	// Account creation timestamp
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last successful login timestamp
	LastLogin pgtype.Timestamptz `json:"last_login"`
	// Account active status (for soft delete)
	IsActive bool `json:"is_active"`
}
