// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDevices(ctx context.Context) (int64, error)
	CountDevicesByStatus(ctx context.Context, status DeviceStatus) (int64, error)
	// IoT Platform - Device Manager Queries
	// SQL queries with sqlc annotations for type-safe code generation
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	DeleteDevice(ctx context.Context, id pgtype.UUID) error
	GetDevice(ctx context.Context, id pgtype.UUID) (Device, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	ListDevicesByStatus(ctx context.Context, arg ListDevicesByStatusParams) ([]Device, error)
	ListDevicesByType(ctx context.Context, arg ListDevicesByTypeParams) ([]Device, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
