// Protocol Buffers version 3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: telemetry/telemetry.proto

// Package for telemetry service

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single telemetry data point
type TelemetryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`    // Unix timestamp
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // Metric value
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`     // Unit of measurement (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPoint) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TelemetryPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryPoint) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Aggregated telemetry data for a time bucket
type TelemetryAggregation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"` // Time bucket (RFC3339 format)
	Avg           float64                `protobuf:"fixed64,2,opt,name=avg,proto3" json:"avg,omitempty"`     // Average value
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`     // Minimum value
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`     // Maximum value
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`  // Number of samples
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAggregation) Reset() {
	*x = TelemetryAggregation{}
	mi := &file_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAggregation) ProtoMessage() {}

func (x *TelemetryAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAggregation.ProtoReflect.Descriptor instead.
func (*TelemetryAggregation) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryAggregation) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TelemetryAggregation) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *TelemetryAggregation) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TelemetryAggregation) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *TelemetryAggregation) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Request to get raw telemetry data
type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // Device UUID
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // Metric name (e.g., "temperature")
	FromTime      int64                  `protobuf:"varint,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`      // Start time (Unix timestamp)
	ToTime        int64                  `protobuf:"varint,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`            // End time (Unix timestamp)
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                            // Maximum number of points (default: 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *GetTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetTelemetryRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *GetTelemetryRequest) GetFromTime() int64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *GetTelemetryRequest) GetToTime() int64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

func (x *GetTelemetryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response with raw telemetry data
type GetTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TelemetryPoint      `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryResponse) Reset() {
	*x = GetTelemetryResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryResponse) ProtoMessage() {}

func (x *GetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *GetTelemetryResponse) GetPoints() []*TelemetryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// Request to get aggregated telemetry data
type GetTelemetryAggregatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // Device UUID
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // Metric name
	FromTime      int64                  `protobuf:"varint,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`      // Start time (Unix timestamp)
	ToTime        int64                  `protobuf:"varint,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`            // End time (Unix timestamp)
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`                       // Aggregation interval (e.g., "1 hour", "1 day")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryAggregatedRequest) Reset() {
	*x = GetTelemetryAggregatedRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryAggregatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryAggregatedRequest) ProtoMessage() {}

func (x *GetTelemetryAggregatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryAggregatedRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryAggregatedRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *GetTelemetryAggregatedRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetTelemetryAggregatedRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *GetTelemetryAggregatedRequest) GetFromTime() int64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *GetTelemetryAggregatedRequest) GetToTime() int64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

func (x *GetTelemetryAggregatedRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

// Response with aggregated telemetry data
type GetTelemetryAggregatedResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Aggregations  []*TelemetryAggregation `protobuf:"bytes,1,rep,name=aggregations,proto3" json:"aggregations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryAggregatedResponse) Reset() {
	*x = GetTelemetryAggregatedResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryAggregatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryAggregatedResponse) ProtoMessage() {}

func (x *GetTelemetryAggregatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryAggregatedResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryAggregatedResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *GetTelemetryAggregatedResponse) GetAggregations() []*TelemetryAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

// Request to get the latest metric value
type GetLatestMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // Device UUID
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // Metric name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestMetricRequest) Reset() {
	*x = GetLatestMetricRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestMetricRequest) ProtoMessage() {}

func (x *GetLatestMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestMetricRequest.ProtoReflect.Descriptor instead.
func (*GetLatestMetricRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestMetricRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetLatestMetricRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

// Response with the latest metric value
type GetLatestMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *TelemetryPoint        `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestMetricResponse) Reset() {
	*x = GetLatestMetricResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestMetricResponse) ProtoMessage() {}

func (x *GetLatestMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestMetricResponse.ProtoReflect.Descriptor instead.
func (*GetLatestMetricResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *GetLatestMetricResponse) GetPoint() *TelemetryPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

// Request to get all available metrics for a device
type GetDeviceMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // Device UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMetricsRequest) Reset() {
	*x = GetDeviceMetricsRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMetricsRequest) ProtoMessage() {}

func (x *GetDeviceMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceMetricsRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceMetricsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// Response with list of metric names
type GetDeviceMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []string               `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMetricsResponse) Reset() {
	*x = GetDeviceMetricsResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMetricsResponse) ProtoMessage() {}

func (x *GetDeviceMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceMetricsResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceMetricsResponse) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x19telemetry/telemetry.proto\x12\ttelemetry\"N\n" +
	"\x0eTelemetryPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"z\n" +
	"\x14TelemetryAggregation\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03avg\x18\x02 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\"\x9f\x01\n" +
	"\x13GetTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x1b\n" +
	"\tfrom_time\x18\x03 \x01(\x03R\bfromTime\x12\x17\n" +
	"\ato_time\x18\x04 \x01(\x03R\x06toTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"I\n" +
	"\x14GetTelemetryResponse\x121\n" +
	"\x06points\x18\x01 \x03(\v2\x19.telemetry.TelemetryPointR\x06points\"\xaf\x01\n" +
	"\x1dGetTelemetryAggregatedRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x1b\n" +
	"\tfrom_time\x18\x03 \x01(\x03R\bfromTime\x12\x17\n" +
	"\ato_time\x18\x04 \x01(\x03R\x06toTime\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\"e\n" +
	"\x1eGetTelemetryAggregatedResponse\x12C\n" +
	"\faggregations\x18\x01 \x03(\v2\x1f.telemetry.TelemetryAggregationR\faggregations\"V\n" +
	"\x16GetLatestMetricRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\"J\n" +
	"\x17GetLatestMetricResponse\x12/\n" +
	"\x05point\x18\x01 \x01(\v2\x19.telemetry.TelemetryPointR\x05point\"6\n" +
	"\x17GetDeviceMetricsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"4\n" +
	"\x18GetDeviceMetricsResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x03(\tR\ametrics2\x89\x03\n" +
	"\x10TelemetryService\x12O\n" +
	"\fGetTelemetry\x12\x1e.telemetry.GetTelemetryRequest\x1a\x1f.telemetry.GetTelemetryResponse\x12m\n" +
	"\x16GetTelemetryAggregated\x12(.telemetry.GetTelemetryAggregatedRequest\x1a).telemetry.GetTelemetryAggregatedResponse\x12X\n" +
	"\x0fGetLatestMetric\x12!.telemetry.GetLatestMetricRequest\x1a\".telemetry.GetLatestMetricResponse\x12[\n" +
	"\x10GetDeviceMetrics\x12\".telemetry.GetDeviceMetricsRequest\x1a#.telemetry.GetDeviceMetricsResponseB=Z;github.com/yourusername/iot-platform/shared/proto/telemetryb\x06proto3"

var (
	file_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_telemetry_proto_rawDescData []byte
)

func file_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_proto_rawDesc), len(file_telemetry_telemetry_proto_rawDesc)))
	})
	return file_telemetry_telemetry_proto_rawDescData
}

var file_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_telemetry_telemetry_proto_goTypes = []any{
	(*TelemetryPoint)(nil),                 // 0: telemetry.TelemetryPoint
	(*TelemetryAggregation)(nil),           // 1: telemetry.TelemetryAggregation
	(*GetTelemetryRequest)(nil),            // 2: telemetry.GetTelemetryRequest
	(*GetTelemetryResponse)(nil),           // 3: telemetry.GetTelemetryResponse
	(*GetTelemetryAggregatedRequest)(nil),  // 4: telemetry.GetTelemetryAggregatedRequest
	(*GetTelemetryAggregatedResponse)(nil), // 5: telemetry.GetTelemetryAggregatedResponse
	(*GetLatestMetricRequest)(nil),         // 6: telemetry.GetLatestMetricRequest
	(*GetLatestMetricResponse)(nil),        // 7: telemetry.GetLatestMetricResponse
	(*GetDeviceMetricsRequest)(nil),        // 8: telemetry.GetDeviceMetricsRequest
	(*GetDeviceMetricsResponse)(nil),       // 9: telemetry.GetDeviceMetricsResponse
}
var file_telemetry_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.GetTelemetryResponse.points:type_name -> telemetry.TelemetryPoint
	1, // 1: telemetry.GetTelemetryAggregatedResponse.aggregations:type_name -> telemetry.TelemetryAggregation
	0, // 2: telemetry.GetLatestMetricResponse.point:type_name -> telemetry.TelemetryPoint
	2, // 3: telemetry.TelemetryService.GetTelemetry:input_type -> telemetry.GetTelemetryRequest
	4, // 4: telemetry.TelemetryService.GetTelemetryAggregated:input_type -> telemetry.GetTelemetryAggregatedRequest
	6, // 5: telemetry.TelemetryService.GetLatestMetric:input_type -> telemetry.GetLatestMetricRequest
	8, // 6: telemetry.TelemetryService.GetDeviceMetrics:input_type -> telemetry.GetDeviceMetricsRequest
	3, // 7: telemetry.TelemetryService.GetTelemetry:output_type -> telemetry.GetTelemetryResponse
	5, // 8: telemetry.TelemetryService.GetTelemetryAggregated:output_type -> telemetry.GetTelemetryAggregatedResponse
	7, // 9: telemetry.TelemetryService.GetLatestMetric:output_type -> telemetry.GetLatestMetricResponse
	9, // 10: telemetry.TelemetryService.GetDeviceMetrics:output_type -> telemetry.GetDeviceMetricsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_telemetry_proto_init() }
func file_telemetry_telemetry_proto_init() {
	if File_telemetry_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_proto_rawDesc), len(file_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_telemetry_proto = out.File
	file_telemetry_telemetry_proto_goTypes = nil
	file_telemetry_telemetry_proto_depIdxs = nil
}
