// Protocol Buffers version 3

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: telemetry/telemetry.proto

// Package for telemetry service

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_GetTelemetry_FullMethodName           = "/telemetry.TelemetryService/GetTelemetry"
	TelemetryService_GetTelemetryAggregated_FullMethodName = "/telemetry.TelemetryService/GetTelemetryAggregated"
	TelemetryService_GetLatestMetric_FullMethodName        = "/telemetry.TelemetryService/GetLatestMetric"
	TelemetryService_GetDeviceMetrics_FullMethodName       = "/telemetry.TelemetryService/GetDeviceMetrics"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Telemetry service for querying device telemetry data
type TelemetryServiceClient interface {
	// Get raw telemetry data within a time range
	GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error)
	// Get aggregated telemetry data (for charts/dashboards)
	GetTelemetryAggregated(ctx context.Context, in *GetTelemetryAggregatedRequest, opts ...grpc.CallOption) (*GetTelemetryAggregatedResponse, error)
	// Get the latest value for a specific metric
	GetLatestMetric(ctx context.Context, in *GetLatestMetricRequest, opts ...grpc.CallOption) (*GetLatestMetricResponse, error)
	// Get all available metrics for a device
	GetDeviceMetrics(ctx context.Context, in *GetDeviceMetricsRequest, opts ...grpc.CallOption) (*GetDeviceMetricsResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetTelemetryAggregated(ctx context.Context, in *GetTelemetryAggregatedRequest, opts ...grpc.CallOption) (*GetTelemetryAggregatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetryAggregatedResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetTelemetryAggregated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetLatestMetric(ctx context.Context, in *GetLatestMetricRequest, opts ...grpc.CallOption) (*GetLatestMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestMetricResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetLatestMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetDeviceMetrics(ctx context.Context, in *GetDeviceMetricsRequest, opts ...grpc.CallOption) (*GetDeviceMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceMetricsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetDeviceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
//
// Telemetry service for querying device telemetry data
type TelemetryServiceServer interface {
	// Get raw telemetry data within a time range
	GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error)
	// Get aggregated telemetry data (for charts/dashboards)
	GetTelemetryAggregated(context.Context, *GetTelemetryAggregatedRequest) (*GetTelemetryAggregatedResponse, error)
	// Get the latest value for a specific metric
	GetLatestMetric(context.Context, *GetLatestMetricRequest) (*GetLatestMetricResponse, error)
	// Get all available metrics for a device
	GetDeviceMetrics(context.Context, *GetDeviceMetricsRequest) (*GetDeviceMetricsResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) GetTelemetryAggregated(context.Context, *GetTelemetryAggregatedRequest) (*GetTelemetryAggregatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetryAggregated not implemented")
}
func (UnimplementedTelemetryServiceServer) GetLatestMetric(context.Context, *GetLatestMetricRequest) (*GetLatestMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestMetric not implemented")
}
func (UnimplementedTelemetryServiceServer) GetDeviceMetrics(context.Context, *GetDeviceMetricsRequest) (*GetDeviceMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceMetrics not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_GetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetTelemetry(ctx, req.(*GetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetTelemetryAggregated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryAggregatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetTelemetryAggregated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetTelemetryAggregated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetTelemetryAggregated(ctx, req.(*GetTelemetryAggregatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetLatestMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetLatestMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetLatestMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetLatestMetric(ctx, req.(*GetLatestMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetDeviceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetDeviceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetDeviceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetDeviceMetrics(ctx, req.(*GetDeviceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTelemetry",
			Handler:    _TelemetryService_GetTelemetry_Handler,
		},
		{
			MethodName: "GetTelemetryAggregated",
			Handler:    _TelemetryService_GetTelemetryAggregated_Handler,
		},
		{
			MethodName: "GetLatestMetric",
			Handler:    _TelemetryService_GetLatestMetric_Handler,
		},
		{
			MethodName: "GetDeviceMetrics",
			Handler:    _TelemetryService_GetDeviceMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telemetry/telemetry.proto",
}
