// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateDeviceInput struct {
	Name     string                `json:"name"`
	Type     string                `json:"type"`
	Metadata []*MetadataEntryInput `json:"metadata,omitempty"`
}

type DeleteResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Device struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	Status    DeviceStatus     `json:"status"`
	CreatedAt int              `json:"createdAt"`
	LastSeen  int              `json:"lastSeen"`
	Metadata  []*MetadataEntry `json:"metadata"`
}

type DeviceConnection struct {
	Devices  []*Device `json:"devices"`
	Total    int       `json:"total"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MetadataEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type MetadataEntryInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Name     string  `json:"name"`
	Role     *string `json:"role,omitempty"`
}

type Stats struct {
	TotalDevices   int `json:"totalDevices"`
	OnlineDevices  int `json:"onlineDevices"`
	OfflineDevices int `json:"offlineDevices"`
	ErrorDevices   int `json:"errorDevices"`
}

type Subscription struct {
}

type UpdateDeviceInput struct {
	ID       string                `json:"id"`
	Name     *string               `json:"name,omitempty"`
	Status   *DeviceStatus         `json:"status,omitempty"`
	Metadata []*MetadataEntryInput `json:"metadata,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	CreatedAt int    `json:"createdAt"`
	LastLogin *int   `json:"lastLogin,omitempty"`
	IsActive  bool   `json:"isActive"`
}

type DeviceStatus string

const (
	DeviceStatusUnknown     DeviceStatus = "UNKNOWN"
	DeviceStatusOnline      DeviceStatus = "ONLINE"
	DeviceStatusOffline     DeviceStatus = "OFFLINE"
	DeviceStatusError       DeviceStatus = "ERROR"
	DeviceStatusMaintenance DeviceStatus = "MAINTENANCE"
)

var AllDeviceStatus = []DeviceStatus{
	DeviceStatusUnknown,
	DeviceStatusOnline,
	DeviceStatusOffline,
	DeviceStatusError,
	DeviceStatusMaintenance,
}

func (e DeviceStatus) IsValid() bool {
	switch e {
	case DeviceStatusUnknown, DeviceStatusOnline, DeviceStatusOffline, DeviceStatusError, DeviceStatusMaintenance:
		return true
	}
	return false
}

func (e DeviceStatus) String() string {
	return string(e)
}

func (e *DeviceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeviceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeviceStatus", str)
	}
	return nil
}

func (e DeviceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeviceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeviceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
