// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	// IoT Platform - User Service Queries
	// SQL queries with sqlc annotations for type-safe code generation
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetPasswordHash(ctx context.Context, email string) (string, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
